# config.yaml
data:
  dataset: TGCA-RENAL 
  class_descriptions:  tdata/tgca-renal_class_descriptions.json 
  num_shots: 10  # K-shot patches per class
  num_wsis: 16   # Bag-level WSIs
  patches_per_wsi: 1000
model:
  clip_model: ViT-B-32
  vqgan_codebook_size: 1000
  prototypes_per_class: 10
  n_classes: 10
  feature_dim: 512
  lora_rank: 8
  beta: 0.6
  gamma: 0.7
  tau: 0.1
  alpha: 10.0
training:
  epochs: 10
  batch_size: 256
  learning_rate: 1e-4
  device: cuda