paths:
  source_dir: "/home/mvu9/datasets/TCGA-datasets/KICH"
  save_dir: "/home/mvu9/processing_datasets/processing_tcga_256/kich"
  patch_h5_dir: "/home/mvu9/processing_datasets/processing_tcga_256/kich/patches_h5"
  # patch_png_dir: "/home/mvu9/processing_datasets/processing_tcga_256/kich/patches_png"
  patch_png_dir:
    patch_256x256_10x: "/home/mvu9/processing_datasets/processing_tcga_256/kich/png_patches/patch_256x256_10x"
    patch_256x256_5x:  "/home/mvu9/processing_datasets/processing_tcga_256/kich/png_patches/patch_256x256_5x" 
  mask_save_dir: "/home/mvu9/processing_datasets/processing_tcga_256/kich/masks"
  only_mask_save_dir: "/home/mvu9/processing_datasets/processing_tcga_256/kich/only_masks"
  stitch_save_dir: "/home/mvu9/processing_datasets/processing_tcga_256/kich/graph_1024"
  slide_name_file: "/home/mvu9/datasets/TCGA-metadata/KICH/slides.xlsx"
  uuid_name_file: "/home/mvu9/datasets/TCGA-metadata/KICH/uuids.xlsx"
  preset_file: "/home/mvu9/folder_04_ma/wsi-data/presets/tcga_vilamil.csv"
  slide_list:  "/home/mvu9/processing_datasets/processing_tcga_256/kich/process_list_autogen.csv" 
  missing_patches_h5: "/home/mvu9/processing_datasets/missing_files/patches_h5/kich.csv"
  missing_pt_files: "/home/mvu9/processing_datasets/missing_files/pt_files/kich.csv" 
# Processing parameters
processing:
  patch_size: 1024
  step_size: 1024
  patch_level: 0
  seg: true
  patch: true
  stitch: false
  auto_skip: true

feature_extraction:
  model_name: "resnet50_trunc"
  batch_size: 256
  target_patch_size: 224
  slide_ext: ".svs"  # Adjust if TCGA-KICH uses .tif or other format
  no_auto_skip: false  # Inverted from processing.auto_skip