source: 
save_dir: /path/to/output
patch_save_dir: /path/to/output/patches_256
mask_save_dir: /path/to/output/masks
only_mask_save_dir: /path/to/output/only_masks
stitch_save_dir: /path/to/output/graph_256
slide_name_file: slides.xlsx
uuid_name_file: slide_info.xlsx
patch_size: 256
step_size: 256
patch_level: 0
seg: true
patch: true
stitch: true
save_mask: true
auto_skip: true
process_list: null
seg_params:
  seg_level: -1
  sthresh: 8
  mthresh: 7
  close: 4
  use_otsu: false
  keep_ids: none
  exclude_ids: none
filter_params:
  a_t: 100
  a_h: 16
  max_n_holes: 8
vis_params:
  vis_level: -1
  line_thickness: 250
patch_params:
  use_padding: true
  contour_fn: four_pt
use_default_params: false

