paths:
  source_dir: "/project/hnguyen2/mvu9/datasets/TGCA-datasets/KICH"
  save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tgca/kich"
  patch_h5_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tgca/kich/patches_h5"
  patch_png_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tgca/kich/patches_png"
  mask_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tgca/kich/masks"
  only_mask_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tgca/kich/only_masks"
  stitch_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tgca/kich/graph_1024"
  slide_name_file: "/project/hnguyen2/mvu9/datasets/TGCA-metadata/KICH/slides.xlsx"
  uuid_name_file: "/project/hnguyen2/mvu9/datasets/TGCA-metadata/KICH/uuids.xlsx"
  preset_file: "./presets/tcga.csv"

# Processing parameters
processing:
  patch_size: 256
  step_size: 256
  patch_level: 1
  seg: true
  patch: true
  stitch: false
  auto_skip: true