dataset_name: 'tcga_renal'
paths: 
  data_folder_s:
    luad: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/luad/conch_features_fp/patch_256x256_5x"
    lusc: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/lusc/conch_features_fp/patch_256x256_5x"

  data_folder_l:
    luad: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/luad/conch_features_fp/patch_256x256_10x"
    lusc: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/lusc/conch_features_fp/patch_256x256_10x"
 
  results_dir: "/project/hnguyen2/mvu9/wsi_fs_results/conch_tcga_lung_results" 
  # split_folder: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/splits_csv_tcga_renal"
  split_folder: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/splits_csv_tcga_lung"

  weight_path: "/project/hnguyen2/mvu9/checkpoints/CONCH"
patch_size: 256 
label_dict: {'KIRP': 0, 'lusc': 1, 'luad': 2} 

model_name: ViLa_MIL_Model # can replace by ViLa_MIL_Model
# you rmodel cofig here 
text_prompt_path: "/project/hnguyen2/mvu9/folder_04_ma/wsi-fs/src/explainer_ver1/text_prompt/TCGA_Lung_two_scale_text_prompt.csv"
prototype_number: 10
# max_epochs: 20
lr: 0.001
label_frac: 1.0
seed: 1
k: 5
k_start: 1
k_end: 1

drop_out: false
opt: adam
bag_loss: ce
weighted_sample: false
early_stopping: true 
n_classes: 3 
log_data: false
reg: 1e-5