dataset_name: 'tcga_renal'
paths: 
  # data_folder_s: # -> replaced by current features_fp/ (folder saved in your computer)
  #   kich: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kich/clip_rn50_features" # will me modified to clip_rn50_features_fp/patch_256x256_5x
  #   kirc: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirc/clip_rn50_features" # will me modified to clip_rn50_features_fp/patch_256x256_5x 
  #   kirp: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/clip_rn50_features" # will me modified to clip_rn50_features_fp/patch_256x256_5x 
  # data_folder_l: 
  #   kich: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kich/clip_rn50_features" # will me modified to clip_rn50_features_fp/patch_256x256_10x
  #   kirc: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirc/clip_rn50_features" # will me modified to clip_rn50_features_fp/patch_256x256_10x 
  #   kirp: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/clip_rn50_features" # will me modified to clip_rn50_features_fp/patch_256x256_10x 
  data_folder_s:
    kich: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kich/conch_features_fp/patch_256x256_5x"
    kirc: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirc/conch_features_fp/patch_256x256_5x"
    kirp: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/conch_features_fp/patch_256x256_5x"

  data_folder_l:
    kich: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kich/conch_features_fp/patch_256x256_10x"
    kirc: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirc/conch_features_fp/patch_256x256_10x"
    kirp: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/conch_features_fp/patch_256x256_10x"
 
  results_dir: "/project/hnguyen2/mvu9/wsi_fs_results/explainer_ver1_tcga_renal_results" 
  # split_folder: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/splits_csv_tcga_renal"
  split_folder: "/project/hnguyen2/mvu9/folder_04_ma/wsi-fs/splits_csv_tcga_renal"

patch_size: 256 
label_dict: {'KIRP': 0, 'KIRC': 1, 'KICH': 2} 

model_name: CONCH_PLIP_adapter_GAT # can replace by ViLa_MIL_Model
# you rmodel cofig here 
text_prompt_path: "/project/hnguyen2/mvu9/folder_04_ma/wsi-fs/src/explainer_ver1/text_prompt/TCGA_RCC_two_scale_text_prompt.csv"
prototype_number: 10
# max_epochs: 20
lr: 0.001
label_frac: 1.0
seed: 1
k: 5
k_start: 1
k_end: 1

drop_out: false
opt: adam
bag_loss: ce
weighted_sample: false
early_stopping: true 
n_classes: 3 
log_data: false
reg: 1e-5

text_encoder_ckpt_dir: '/project/hnguyen2/mvu9/pretrained_checkpoints/PLIP'
# image_encoder_ckpt_dir: /project/hnguyen2/mvu9/pretrained_checkpoints/conch_checkpoints
