prototype_training:
  input_size: 1024
  hidden_size: 512
  prototype_number: 10
  num_classes: 3
  epochs: 10
  lr: 0.0001
  batch_size: 1
  num_classes: 3 
paths:
  split_folder: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/splits_csv_tcga_renal/fold_1" 
  pt_files_dir:
    kich: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kich/features_fp"
    kirp: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/features_fp"
    kirc: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirc/features_fp"
  prototype_out_dir: /project/hnguyen2/mvu9/prototype_outputs/
label_dict: {'KIRP': 0, 'KIRC': 1, 'KICH': 2} 